// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.0
// 	protoc        v3.21.12
// source: agenda.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Agenda struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone string `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
}

func (x *Agenda) Reset() {
	*x = Agenda{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agenda_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Agenda) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agenda) ProtoMessage() {}

func (x *Agenda) ProtoReflect() protoreflect.Message {
	mi := &file_agenda_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agenda.ProtoReflect.Descriptor instead.
func (*Agenda) Descriptor() ([]byte, []int) {
	return file_agenda_proto_rawDescGZIP(), []int{0}
}

func (x *Agenda) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Agenda) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Agenda) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Agenda) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type PingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agenda_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agenda_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_agenda_proto_rawDescGZIP(), []int{1}
}

type PingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response string `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agenda_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agenda_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_agenda_proto_rawDescGZIP(), []int{2}
}

func (x *PingResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type CreateAgendaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Agenda *Agenda `protobuf:"bytes,1,opt,name=agenda,proto3" json:"agenda,omitempty"`
}

func (x *CreateAgendaRequest) Reset() {
	*x = CreateAgendaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agenda_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAgendaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAgendaRequest) ProtoMessage() {}

func (x *CreateAgendaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agenda_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAgendaRequest.ProtoReflect.Descriptor instead.
func (*CreateAgendaRequest) Descriptor() ([]byte, []int) {
	return file_agenda_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAgendaRequest) GetAgenda() *Agenda {
	if x != nil {
		return x.Agenda
	}
	return nil
}

type CreateAgendaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Agenda *Agenda `protobuf:"bytes,1,opt,name=agenda,proto3" json:"agenda,omitempty"`
}

func (x *CreateAgendaResponse) Reset() {
	*x = CreateAgendaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agenda_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAgendaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAgendaResponse) ProtoMessage() {}

func (x *CreateAgendaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agenda_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAgendaResponse.ProtoReflect.Descriptor instead.
func (*CreateAgendaResponse) Descriptor() ([]byte, []int) {
	return file_agenda_proto_rawDescGZIP(), []int{4}
}

func (x *CreateAgendaResponse) GetAgenda() *Agenda {
	if x != nil {
		return x.Agenda
	}
	return nil
}

type GetAgendaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetAgendaRequest) Reset() {
	*x = GetAgendaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agenda_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAgendaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgendaRequest) ProtoMessage() {}

func (x *GetAgendaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agenda_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgendaRequest.ProtoReflect.Descriptor instead.
func (*GetAgendaRequest) Descriptor() ([]byte, []int) {
	return file_agenda_proto_rawDescGZIP(), []int{5}
}

func (x *GetAgendaRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAgendaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Agenda *Agenda `protobuf:"bytes,1,opt,name=agenda,proto3" json:"agenda,omitempty"`
}

func (x *GetAgendaResponse) Reset() {
	*x = GetAgendaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agenda_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAgendaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgendaResponse) ProtoMessage() {}

func (x *GetAgendaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agenda_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgendaResponse.ProtoReflect.Descriptor instead.
func (*GetAgendaResponse) Descriptor() ([]byte, []int) {
	return file_agenda_proto_rawDescGZIP(), []int{6}
}

func (x *GetAgendaResponse) GetAgenda() *Agenda {
	if x != nil {
		return x.Agenda
	}
	return nil
}

type GetAgendasRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page  int64 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Items int64 `protobuf:"varint,2,opt,name=items,proto3" json:"items,omitempty"`
}

func (x *GetAgendasRequest) Reset() {
	*x = GetAgendasRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agenda_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAgendasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgendasRequest) ProtoMessage() {}

func (x *GetAgendasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agenda_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgendasRequest.ProtoReflect.Descriptor instead.
func (*GetAgendasRequest) Descriptor() ([]byte, []int) {
	return file_agenda_proto_rawDescGZIP(), []int{7}
}

func (x *GetAgendasRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAgendasRequest) GetItems() int64 {
	if x != nil {
		return x.Items
	}
	return 0
}

type GetAgendasResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Agendas  []*Agenda `protobuf:"bytes,1,rep,name=agendas,proto3" json:"agendas,omitempty"`
	Total    int64     `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	NextPage int64     `protobuf:"varint,3,opt,name=next_page,json=nextPage,proto3" json:"next_page,omitempty"`
}

func (x *GetAgendasResponse) Reset() {
	*x = GetAgendasResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agenda_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAgendasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgendasResponse) ProtoMessage() {}

func (x *GetAgendasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agenda_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgendasResponse.ProtoReflect.Descriptor instead.
func (*GetAgendasResponse) Descriptor() ([]byte, []int) {
	return file_agenda_proto_rawDescGZIP(), []int{8}
}

func (x *GetAgendasResponse) GetAgendas() []*Agenda {
	if x != nil {
		return x.Agendas
	}
	return nil
}

func (x *GetAgendasResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetAgendasResponse) GetNextPage() int64 {
	if x != nil {
		return x.NextPage
	}
	return 0
}

type UpdateAgendaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Agenda *Agenda `protobuf:"bytes,2,opt,name=agenda,proto3" json:"agenda,omitempty"`
}

func (x *UpdateAgendaRequest) Reset() {
	*x = UpdateAgendaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agenda_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAgendaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAgendaRequest) ProtoMessage() {}

func (x *UpdateAgendaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agenda_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAgendaRequest.ProtoReflect.Descriptor instead.
func (*UpdateAgendaRequest) Descriptor() ([]byte, []int) {
	return file_agenda_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateAgendaRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateAgendaRequest) GetAgenda() *Agenda {
	if x != nil {
		return x.Agenda
	}
	return nil
}

type UpdateAgendaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Agenda *Agenda `protobuf:"bytes,1,opt,name=agenda,proto3" json:"agenda,omitempty"`
}

func (x *UpdateAgendaResponse) Reset() {
	*x = UpdateAgendaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agenda_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAgendaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAgendaResponse) ProtoMessage() {}

func (x *UpdateAgendaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agenda_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAgendaResponse.ProtoReflect.Descriptor instead.
func (*UpdateAgendaResponse) Descriptor() ([]byte, []int) {
	return file_agenda_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateAgendaResponse) GetAgenda() *Agenda {
	if x != nil {
		return x.Agenda
	}
	return nil
}

type DeleteAgendaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteAgendaRequest) Reset() {
	*x = DeleteAgendaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agenda_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAgendaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAgendaRequest) ProtoMessage() {}

func (x *DeleteAgendaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agenda_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAgendaRequest.ProtoReflect.Descriptor instead.
func (*DeleteAgendaRequest) Descriptor() ([]byte, []int) {
	return file_agenda_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteAgendaRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteAgendaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteAgendaResponse) Reset() {
	*x = DeleteAgendaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agenda_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAgendaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAgendaResponse) ProtoMessage() {}

func (x *DeleteAgendaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agenda_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAgendaResponse.ProtoReflect.Descriptor instead.
func (*DeleteAgendaResponse) Descriptor() ([]byte, []int) {
	return file_agenda_proto_rawDescGZIP(), []int{12}
}

var File_agenda_proto protoreflect.FileDescriptor

var file_agenda_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x61, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09,
	0x61, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x2e, 0x76, 0x31, 0x22, 0x58, 0x0a, 0x06, 0x41, 0x67, 0x65,
	0x6e, 0x64, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x14, 0x0a,
	0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68,
	0x6f, 0x6e, 0x65, 0x22, 0x0d, 0x0a, 0x0b, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x2a, 0x0a, 0x0c, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x40,
	0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x06, 0x61, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x2e, 0x76,
	0x31, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x52, 0x06, 0x61, 0x67, 0x65, 0x6e, 0x64, 0x61,
	0x22, 0x41, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x64, 0x61,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x06, 0x61, 0x67, 0x65, 0x6e,
	0x64, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x64,
	0x61, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x52, 0x06, 0x61, 0x67, 0x65,
	0x6e, 0x64, 0x61, 0x22, 0x22, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x64, 0x61,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3e, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x41, 0x67,
	0x65, 0x6e, 0x64, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x06,
	0x61, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61,
	0x67, 0x65, 0x6e, 0x64, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x52,
	0x06, 0x61, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x22, 0x3d, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x41, 0x67,
	0x65, 0x6e, 0x64, 0x61, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x74, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x41, 0x67, 0x65,
	0x6e, 0x64, 0x61, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x07,
	0x61, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x61, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x64, 0x61,
	0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12,
	0x1b, 0x0a, 0x09, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x6e, 0x65, 0x78, 0x74, 0x50, 0x61, 0x67, 0x65, 0x22, 0x50, 0x0a, 0x13,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x29, 0x0a, 0x06, 0x61, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x2e, 0x76, 0x31, 0x2e,
	0x41, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x52, 0x06, 0x61, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x22, 0x41,
	0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x06, 0x61, 0x67, 0x65, 0x6e, 0x64, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x2e,
	0x76, 0x31, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x52, 0x06, 0x61, 0x67, 0x65, 0x6e, 0x64,
	0x61, 0x22, 0x25, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x64,
	0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x16, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x32, 0xce, 0x03, 0x0a, 0x0d, 0x41, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x37, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x2e, 0x61, 0x67, 0x65,
	0x6e, 0x64, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x17, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x50,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a, 0x0c, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x12, 0x1e, 0x2e, 0x61, 0x67,
	0x65, 0x6e, 0x64, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x67,
	0x65, 0x6e, 0x64, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x61, 0x67,
	0x65, 0x6e, 0x64, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x67,
	0x65, 0x6e, 0x64, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x09,
	0x47, 0x65, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x12, 0x1b, 0x2e, 0x61, 0x67, 0x65, 0x6e,
	0x64, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x64,
	0x61, 0x73, 0x12, 0x1c, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1d, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74,
	0x41, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x4f, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x12,
	0x1e, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1f, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x4f, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x64, 0x61,
	0x12, 0x1e, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1f, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x13, 0x5a, 0x11, 0x61, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_agenda_proto_rawDescOnce sync.Once
	file_agenda_proto_rawDescData = file_agenda_proto_rawDesc
)

func file_agenda_proto_rawDescGZIP() []byte {
	file_agenda_proto_rawDescOnce.Do(func() {
		file_agenda_proto_rawDescData = protoimpl.X.CompressGZIP(file_agenda_proto_rawDescData)
	})
	return file_agenda_proto_rawDescData
}

var file_agenda_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_agenda_proto_goTypes = []interface{}{
	(*Agenda)(nil),               // 0: agenda.v1.Agenda
	(*PingRequest)(nil),          // 1: agenda.v1.PingRequest
	(*PingResponse)(nil),         // 2: agenda.v1.PingResponse
	(*CreateAgendaRequest)(nil),  // 3: agenda.v1.CreateAgendaRequest
	(*CreateAgendaResponse)(nil), // 4: agenda.v1.CreateAgendaResponse
	(*GetAgendaRequest)(nil),     // 5: agenda.v1.GetAgendaRequest
	(*GetAgendaResponse)(nil),    // 6: agenda.v1.GetAgendaResponse
	(*GetAgendasRequest)(nil),    // 7: agenda.v1.GetAgendasRequest
	(*GetAgendasResponse)(nil),   // 8: agenda.v1.GetAgendasResponse
	(*UpdateAgendaRequest)(nil),  // 9: agenda.v1.UpdateAgendaRequest
	(*UpdateAgendaResponse)(nil), // 10: agenda.v1.UpdateAgendaResponse
	(*DeleteAgendaRequest)(nil),  // 11: agenda.v1.DeleteAgendaRequest
	(*DeleteAgendaResponse)(nil), // 12: agenda.v1.DeleteAgendaResponse
}
var file_agenda_proto_depIdxs = []int32{
	0,  // 0: agenda.v1.CreateAgendaRequest.agenda:type_name -> agenda.v1.Agenda
	0,  // 1: agenda.v1.CreateAgendaResponse.agenda:type_name -> agenda.v1.Agenda
	0,  // 2: agenda.v1.GetAgendaResponse.agenda:type_name -> agenda.v1.Agenda
	0,  // 3: agenda.v1.GetAgendasResponse.agendas:type_name -> agenda.v1.Agenda
	0,  // 4: agenda.v1.UpdateAgendaRequest.agenda:type_name -> agenda.v1.Agenda
	0,  // 5: agenda.v1.UpdateAgendaResponse.agenda:type_name -> agenda.v1.Agenda
	1,  // 6: agenda.v1.AgendaService.Ping:input_type -> agenda.v1.PingRequest
	3,  // 7: agenda.v1.AgendaService.CreateAgenda:input_type -> agenda.v1.CreateAgendaRequest
	5,  // 8: agenda.v1.AgendaService.GetAgenda:input_type -> agenda.v1.GetAgendaRequest
	7,  // 9: agenda.v1.AgendaService.GetAgendas:input_type -> agenda.v1.GetAgendasRequest
	9,  // 10: agenda.v1.AgendaService.UpdateAgenda:input_type -> agenda.v1.UpdateAgendaRequest
	11, // 11: agenda.v1.AgendaService.DeleteAgenda:input_type -> agenda.v1.DeleteAgendaRequest
	2,  // 12: agenda.v1.AgendaService.Ping:output_type -> agenda.v1.PingResponse
	4,  // 13: agenda.v1.AgendaService.CreateAgenda:output_type -> agenda.v1.CreateAgendaResponse
	6,  // 14: agenda.v1.AgendaService.GetAgenda:output_type -> agenda.v1.GetAgendaResponse
	8,  // 15: agenda.v1.AgendaService.GetAgendas:output_type -> agenda.v1.GetAgendasResponse
	10, // 16: agenda.v1.AgendaService.UpdateAgenda:output_type -> agenda.v1.UpdateAgendaResponse
	12, // 17: agenda.v1.AgendaService.DeleteAgenda:output_type -> agenda.v1.DeleteAgendaResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_agenda_proto_init() }
func file_agenda_proto_init() {
	if File_agenda_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_agenda_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Agenda); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agenda_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agenda_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agenda_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAgendaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agenda_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAgendaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agenda_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAgendaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agenda_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAgendaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agenda_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAgendasRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agenda_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAgendasResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agenda_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAgendaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agenda_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAgendaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agenda_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAgendaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agenda_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAgendaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_agenda_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agenda_proto_goTypes,
		DependencyIndexes: file_agenda_proto_depIdxs,
		MessageInfos:      file_agenda_proto_msgTypes,
	}.Build()
	File_agenda_proto = out.File
	file_agenda_proto_rawDesc = nil
	file_agenda_proto_goTypes = nil
	file_agenda_proto_depIdxs = nil
}
